---
# This is the Playbook that Ansible will execute
- name: Deploy Containerized Web App
  hosts: deployment  
  become: yes        

  vars:
    image_name: hepziba/devops-project:latest 
    container_name: devops-web-app

  tasks:
    # DELETED OR COMMENTED OUT THIS TASK:
    # - name: Ensure Docker Python module is installed
    #   pip:
    #     name: docker
    #     state: present

    - name: Pull the latest Docker image from the registry
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull
        state: present

    - name: Stop and remove the existing container (if running)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes 

    - name: Run the new container from the pulled image
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "80:3000" 
        restart_policy: always